### GET request to example server
GET http://localhost:8080/api/v1/animals/

### GET first one
GET http://localhost:8080/api/v1/animals/3

### DELETE third one
DELETE http://localhost:8080/api/v1/animals/67040f7fdf9adc72de9960f4

### Create one
POST http://localhost:8080/api/v1/animals/
Content-Type: application/json

{
  "name": "name4",
  "age": 2,
  "sex": "M",
  "description": "description3",
  "location": "location3",
  "type": "dog",
  "photos": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww",
  "shelterId": "1",
  "sterilization": true,
  "availableForAdoption": false
}

#### Update one
PUT http://localhost:8080/api/v1/animals/5
Content-Type: application/json

{
  "name": "Dave The Magical Cheese Wizard))"
}